name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version-file: .nvmrc

      - name: Install dependencies
        run: npm ci --prefer-offline

      - name: Disable Forge telemetry
        run: npx forge settings set usage-analytics false

      - name: Lint codebase
        run: npm run lint
        env:
          FORGE_API_TOKEN: ${{ secrets.FORGE_API_TOKEN }}
          FORGE_EMAIL: ${{ secrets.FORGE_EMAIL }}

      - name: Type check
        run: npm run lint:tsc

      - name: Build app
        run: npm run build
